### ISSUE TITLE
Bug report: Works great on chrome but not on Safari (desktop or mobile iOS 14.2)

### ISSUE THREAD

**Issue by inglesuniversal** [gfyoung/basic-tts#53]
Hope you can fix the issue

Regards

**Comment by gfyoung** [comment]
@inglesuniversal: the APIs used by this package should be supported on Safari.  What problems are you encountering?

**Comment by inglesuniversal** [comment]
No audio output and no errors shown on console. Tested on iOS 14.4 and MacOS Big Sur latest update. If I can help you pinpoint the bug let me know. I think is won't play the default voice you are setting up, since it only works on Chrome Browsers.

**Comment by gfyoung** [comment]
@inglesuniversal: Suggestions to make this library compatible with the latest Safari are welcome!

> I think is won't play the default voice you are setting up, since it only works on Chrome Browsers.

It does work on Safari last I checked, though I do not have Big Sur or iOS 14.4 at the moment.

What happens if you try something like this:

~~~
window.speechSynthesis.speak(new SpeechSynthesisUtterance("Hello world"))
~~~

Trying to understand if this is an issue with compatibility or a library bug.

**Comment by inglesuniversal** [comment]
Thanks for the TIP.

I think I know what happens.

It is not a problem with iOS devices or MacOS supporting it... 

It has to do with the default voice that the script has, it targets or picks a voice created by Google thus it only works best on Chrome Browser.

It would be AWESOME if there is a way for the developer to preset not only a language but a favorite voice (persona) according to the device it is playing on 

e.g.  Paulina (es-MX)    or     Samantha (en-US)   these two are my favorite voices for iPhone / iPad / MacOS for years

if you need additional tests let me know.

**Comment by gfyoung** [comment]
What happens if you do something like this?

~~~javascript
const speaker = new Speaker({lang: "es-MX", speaker: "Paulina"});
~~~

See: https://github.com/gfyoung/basic-tts/blob/master/basic-tts.js#L169-L195

**Comment by inglesuniversal** [comment]
Question: Should I change that line inside the .js file or index.html file?

const speaker = new Speaker({lang: "es-MX", speaker: "Paulina"});

**Comment by gfyoung** [comment]
I made the demo more flexible by introducing a dropdown for the voice.

You can try it out here:

https://gfyoung.github.io/basic-tts/demo.html
